### ISSUE TITLE
engine named 'igor' hasn't been registered with the SelectorEngineRegistry

### ISSUE THREAD

**Issue by santhanakrishnan** [dhemery/igor#11]
Hi Dhemery,

I ran the below code 
private static final IosViewIdentifier createAccount = igor("UITextFieldLabel[accessibilityLabel=='Email Address']");
    @Test
    public void testA() {
        Thread.sleep(10000);
        IosView button = application().view(createAccount);
        button.sendMessage("touch");
}

and facing the error 

 Operation failed
   Target    : igor UITextFieldLabel[accessibilityLabel=='Email Address']
   Operation : touch []
   Reason    : invalid selector
   Details   : engine named 'igor' hasn't been registered with the SelectorEngineRegistry18:36:53.859  INFO - Stop Simulator --> killall [iPhone Simulator]

Please ping point where I went wrong.

**Comment by dhemery** [comment]
This likely means that you have not linked libIgor.a into your Frankified application.
