### ISSUE TITLE
Search all windows (not only key window)

### ISSUE THREAD

**Issue by dhemery** [dhemery/igor#3]
Add syntax to search all windows.  Caret indicates 'all windows,' so:

```
^ UIKeyboardLayoutStar
```

finds `UIKeyboardLayoutStar` views in all windows.

The caret must be the first non-whitespace character in the query.

Possibility: The caret may combine with a normal instance pattern to select which windows are inspected.

**Comment by dhemery** [comment]
Possibility: The caret excludes the key window. Or maybe this can be handled by predicates. (Can predicates examine an object's class?)

**Comment by lukeredpath** [comment]
@dhemery I'm currently trying to implement this, using the new FEX_windows category method in Frank, as it's otherwise impossible to find alert views on iOS7.

I don't feel there should be special syntax for this; Shelley already finds across all windows so it seems like Igor should do the same.

**Comment by dhemery** [comment]
Oh, good. 

No need for a pull request. I will start on this now, and push it to master when the new method appears in a Frank release.

**Comment by lukeredpath** [comment]
@dhemery take a look at this:
https://github.com/lukeredpath/igor/tree/add-support-for-multiple-windows

It currently depends on this though:
https://github.com/moredip/Frank/pull/250

It is possible without the change to Frank but I think the protocol change is nicer.

**Comment by dhemery** [comment]
Thanks. I might stuff the loop into the Igor class.

What is the likelihood that this will break users' tests? Suppose a selector matches a view in the key window and another view in an alert window.

**Comment by lukeredpath** [comment]
I'd say the chances are slim, but it's not impossible I guess.

**Comment by dhemery** [comment]
It's in the **develop** branch: https://github.com/dhemery/igor/commit/7e0c4af940ac6aeaa2c4f4c0d0812903b70cfbfc

(I give myself permission rebase that branch, so be careful.)

**Comment by lukeredpath** [comment]
Great. Incidentally, I did run into an issue with my tests picking up matching elements in different windows (I've got some custom modal code that uses a new window) and it turned out quite easy to workaround by only selecting views in the key window, by prepending `UIWindow[keyWindow=1]` to my query. I even rolled this into my Igor Ruby library (still not released yet) so I can say things like this:

``` ruby
Igor::Query.new('UIButton*').labelled('Send').in_key_window
```

**Comment by lukeredpath** [comment]
Frank support for the extended protocol should be coming soon, I've just got a few things to fix on https://github.com/moredip/Frank/pull/250

**Comment by lukeredpath** [comment]
@dhemery my pull request got merged into Frank, so if you're happy this issue could probably be closed now.
